WIP: Add tensor representation and EDCPTD centrality calculation
se-passau/coronet pull request #173
Opened 2019-10-21 09:54 UTC by fehnkera

Functions that enable to represent OSS projects as forth-order tensors and to calculate EDCPTD centrality on them are added to a temporary file 'util-tensor.R'. The functions are not final. Feedback and discussions are welcome.

Signed-off-by: Anselm Fehnker <anselm@muenster.de>

### Prerequisites

- [ ] I adhere to the coding conventions (described [here](https://github.com/se-passau/coronet/blob/master/CONTRIBUTING.md)) in my code.
- [ ] I have updated the copyright headers of the files I have modified.
- [ ] I have written appropriate commit messages, i.e., I have recorded the goal, the need, the needed changes, and the location of my code modifications for each commit. This includes also, e.g., referencing to relevant issues.
- [ ] I have put signed-off tags in *all* commits.
- [ ] I have updated the changelog file [NEWS.md](https://github.com/se-passau/coronet/blob/master/NEWS.md) appropriately.
- [ ] The pull request is opened against the branch `dev`.

### Description

### Changelog

2019-10-21 09:55 UTC, fehnkera commented on util-tensor.R
> +EDCPTD.centrality = function(network.builder){
I didn't knew how the project data gets available for the function, so I just gave the function a ```network.builder``` object as a parameter. Thats probably not the way how it is done usually. How exactly is it proposed to be implemented. Are there any similiar functions in the project I can refer to?

2019-10-21 09:56 UTC, fehnkera commented on util-tensor.R
> +    return(edcptd)
The results are currently returned as a data frame in which one column contains the names of the developers and one column contains their EDCPTD score. What exactly is the wanted format for the EDCPTD results. Again are there already similiar functions in the project?

2019-10-21 09:56 UTC, fehnkera commented on util-tensor.R
> +    mail.network = network.builder$get.author.network()
At the moment I make a single call for each of the mail, the cochange and the issue network. Is there a better way to get the three networks?

2019-10-21 09:57 UTC, fehnkera commented on util-tensor.R
> +    }
To test if the data source exist for the project, I check whether the corresponding network has vertices. Is there a better way to check this?

2019-10-21 09:57 UTC, fehnkera commented on util-tensor.R
> +}
This method is mostly copied from the script of @Angelika1 in ```dev-network-growth```. What does this mean for the copyright and the documentation of the code?

2019-10-21 09:58 UTC, fehnkera commented on util-tensor.R
> +}
Again this method is mostly copied from the script in dev-network-growth.

2019-11-05 13:58 UTC, clhunsen submitted a review, later dismissed
Hi @fehnkera!

Thank you very much for your effort to bring this functionality to coronet! :grinning::+1: I had a quick look at your changes/additions and identified some issues that need to be solved. I tried my best to give you some guidance in my comments to solve them appropriately. :slightly_smiling_face: 

There are mainly the following things to do:
- Adaptation of the code to the coding conventions,
- addition of license and copyright headers,
- potential movement of functions to other files (open question), and 
- addition of information to the file `README.md`.

As always, please do not hesitate to ask if you have any questions. If you do not have any time left, please tell us (we will likely adopt this PR then).

2019-11-05 17:04 UTC, bockthom commented on util-tensor.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE){
> I am not sure whether this function is placed here appropriately. thinking We may want to move it to the file `util-misc.R`. This may also apply for further functions proposed here (e.g., `EDCPTD.centrality` is probably a metric), but I would like to put this off for after all other issues are solved.
> 
> Any ideas are welcome. @ecklbarb, @bockthom, @hechtlC, what are your first thoughts on this?

First of all, I would like to have all changes here in this file in a final way, and at the end, when we have agreed to those changes, I would like to move the different functions to the files they most appropriately suite into. So, I would like to postpone this question until this PR is finished.

(However, I am not sure if `util-misc` is the right place for such functions. Together with the mentioned function, I also would like to move several parts, which are related to this function, from the `util.R` file of `dev-network-growth` to coronet. Maybe we could think about a separate file then. Nevertheless, that's currently out of scope. First adjust this PR, then decide on whether and where to move which function.)

2019-11-05 17:09 UTC, bockthom commented on util-tensor.R
> +      A <- get.adjacency(network, attr = "weight")
That relates to issue se-passau/dev-network-growth/issues/20. In addition, everything which needs to be transferred from the other repository to coronet needs to be adjusted to the coding conventions of coronet, too.

2019-11-05 17:11 UTC, bockthom commented on util-tensor.R
> +}
See also my comments above :wink:

2019-11-06 09:13 UTC, clhunsen commented on util-tensor.R
> +build.tensor.from.adjacency = function(networks, active.developers){
Fair point, I did not thought about that. :+1: 

Another idea on this: Maybe, we can make the argument `active.developers` optional and infer them from the networks if they are not passed to this function. :thinking: This way, we would fulfill both our ideas. :wink:

2020-08-10 11:14 UTC, fehnkera commented on showcase.R
I have added the workflow for calculating EDCPTD centrality with a NetworkBuilder object to the showcase file, if you want to run it. Where shall this be in the long run?

2020-08-11 08:12 UTC, bockthom commented on util-tensor.R
> +## Copyright 2020 by Anselm Fehnker <anselm@muenster.de>
Please adjust your copyright notice to "2019-2020" as most of the work was done in 2019.

In addition, as already criticized in my last review, you also have to add the attributions for all the function you take from the dev-network-growth repository (`get.expanded.adjacency`, `get.author.names.from.networks`, etc.) . That is, you have to check in the other repository who has worked on these functions and when (you can use the blame function of GitHub to browse). Then you need to add a copyright line for each of these persons together with the corresponding year.

2020-08-11 08:12 UTC, bockthom commented on README.md
> +- `rTensor`: For calculating EDCPTD centrality
You added also "Matrix" in install.R. Is this necessary? If so, you need to add this here, too.

2020-08-11 08:13 UTC, bockthom commented on util-tensor.R
> +ForthOrderTensor = R6::R6Class("ForthOrderTensor",
It should be "Fo**u**rthOrderTensor". Please fix that everywhere.

2020-08-11 08:14 UTC, bockthom commented on util-tensor.R
> +       array <-array(0, dim = private$dim)
The coding conventions of this repository are violated in several ways. E.g., use "=" instead of "<-", indentation should be four spaces, etc. Please see CONTRIBUTING.md

2020-08-11 08:15 UTC, bockthom commented on util-tensor.R
> +           array[matrix@i[entry]+1, l, matrix@j[entry]+1, l] = matrix@x[entry]
Could you please add further comments here? I don't understand what's going on here...

2020-08-11 08:16 UTC, bockthom commented on util-tensor.R
> +       private$dim = c(length(private$authors), length(private$relations), length(private$authors), length(private$relations))
Is there a reason that are only getters for relations, authors, and tensor, but none for dim? If so, what is dim used for? Shouldn't we add a getter for that as well?

2020-08-11 08:17 UTC, bockthom commented on util-tensor.R
> +     #' @param weighted bool if the tensor shall be weighted
The default value is missing in the documentation. Please see the contribution guide on how to write proper documentation including default values.

2020-08-11 08:19 UTC, bockthom commented on util-tensor.R
> +get.author.networks = function(network.builder, relations) {
Hm, I am not sure if we really need this function. This a very special case and usually, every list of networks should be suitable. So, every use should build their list of networks by their own. However, we can keep this function for the moment, but we should rename it to something like `get.author.networks.for.multiple.relations`.

2020-08-11 08:23 UTC, bockthom commented on util-tensor.R
> +get.author.names.from.networks = function(networks) {
This function is taken from the dev-network-growth repository. What about its companion to extract them from the data. We should have both functions here.
However, the function is not used here, so we should move it to another file as it is not related to the tensor. Maybe this should be moved to util-misc or a new, separate misc file for all the other functions that follow...

2020-08-11 08:39 UTC, bockthom commented on util-tensor.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE) {
Some as above: This should be moved to another file like "util-networks-misc". In addition, also its companion function which builds cumulated adjacency matrices should be transferred to this file "convert_adjacency_matrix_list_to_array"

2020-08-11 08:40 UTC, bockthom commented on util-tensor.R
> +#' Calculate EDCPTD centrality for a given forth-order tensor.
Could you maybe add a link to a website where is stated how the CDCPTD centrality is calculated?

2020-08-11 08:41 UTC, bockthom commented on util-tensor.R
> +  decomposition <-rTensor::cp(forth.order.tensor$get.tensor(), num_components = 1, max_iter = 50, tol = 1e-05)
Could you explain why these values are chosen?

2020-08-11 08:46 UTC, bockthom commented on showcase.R
It is ok to keep this in the showcase file. Maybe we will move that to somewhere else later on, but for now you have found the right place for it :smile:

2020-08-11 19:23 UTC, clhunsen commented on util-tensor.R
> +#' Calculate EDCPTD centrality for a given forth-order tensor.
Maybe, the authors, title, and DOI of the foundational paper are sufficient.

2020-08-11 19:30 UTC, clhunsen commented on util-tensor.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE) {
> Some as above: This should be moved to another file like "util-networks-misc".

I like the idea of creating another file to obtain a better overview. Maybe, we can move some further functions from the file `util-networks.R` to the new one. E.g., all network-construction functions stay where they are, while any "non-vital" functions are moved.

2020-08-11 19:40 UTC, bockthom commented on util-tensor.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE) {
> Maybe, we can move some further functions from the file util-networks.R to the new one. E.g., all network-construction functions stay where they are, while any "non-vital" functions are moved.

@clhunsen Thanks for the suggestion, sounds really good. However, in this PR, we should first stick to the stuff that is directly related to this pull request. No offence, but the overall goal should be to finish this PR before Anselm will finally leave. Everything else can be discussed afterwards. This PR just includes adding all the utility functions from the other repository and collect them in a new file here, so that they get part of coronet :smile:

2020-08-11 19:43 UTC, bockthom commented on util-tensor.R
> +#' Calculate EDCPTD centrality for a given forth-order tensor.
If there is a website, I would prefer the website as it is easier to access :wink: 
Nevertheless, adding authors, title, and DOI is a good idea :+1:  We should do that independent of whether there is website or not

2020-08-12 13:02 UTC, clhunsen commented on util-tensor.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE) {
Yes, surey you are completely right, @bockthom. This is not a short-term goal, but something for the long run. I just wanted to share my idea so it is not lost in the Nirvana of time. :grin:

2020-08-24 21:44 UTC, bockthom requested changes
@fehnkera Thanks for your changes -- I had a quick look at them and still found lots of lines which violate our contribution guide. Please see my individual review comments below to fix them. I highly suggest to rebase your last commit to fix all the following issues. (If you don't remember interactive rebasing or ammending your last commit, please just let me know, then I can add more details on how to do that.)

In addition to the coding convention issues, there are still some minor parts missing from what we have mentioned in earlier review comments. Please also rebase them into the last commit, thanks!

2020-08-24 21:44 UTC, bockthom commented on showcase.R
> +CASESTUDY = "zeppelin"
please don't change the example, just keep it as it was (i.e., you also need a rebase here, too).

2020-08-24 21:44 UTC, bockthom commented on showcase.R
> +forth.order.tensor = FourthOrderTensor$new(author.networks)
You did correctly adjust the class name, but please also replace the variable `forth.order.tensor` to `fo**u**rth.order.tensor`. Same holds for the comment above (`## create forth-order tensor`)

In addition, please search for "forth" in your scripts and replace all occurrences of them.

2020-08-24 21:44 UTC, bockthom commented on util-init.R
> +source("util-tensor.R")
This is still missing: Add both new files `util-tensor.R` and `util-networks-misc.R` to the `README.md` (roughly, around line 415 in the README). In particular, please comply with the following:

Add the `util-networks-misc.R` directly after `util-networks-covariates.R`, so the order is:
```R
util-networks-metrics.R
util-networks-covariates.R
util-networks-misc.R
util-tensor.R
```
The order of the files should be the same in `util-init.R` as in `README.md`.
For the README, please add the following descriptions:
`util-networks-metrics.R`: Helper functions for network creation (e.g., create adjacency matrices)
`util-tensor.R`: Functionality to build fourth-order tensors

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +        return (active.authors)
As `return` is a function in R, don't use a space after `return` here.

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +get.author.names.from.networks = function(networks) {
In the current `master` of `dev-network-growth`, there is an enhanced, more recent version of this function (enhanced by Jakob). Please use Jakob's enhanced version here (and don't forget to add him to the copyright header then).

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +get.author.names.from.data = function(data.ranges, is.mail.analysis){
Same as above. There is a more recent version of this function.
(And the more recent version already contains `=` instead of ` <-` and a space after `for` and `if`, in compliance with our coding conventions).

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE) {
In the documentation, the default value is still missing.

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +
Maybe I was a little bit imprecise in my last review, but with "companion function" for this function I have meant `get.expanded.adjacency.cumulated`. Sorry for being imprecise. However, the mentioned functions needs to be added to this module, too. (When adding the cumulated function, please don't forget to add Angelika to the copyright header. Somewhere, there is already a copyright header having her name, just look for it and add it here again).

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +    if(igraph::vcount(network) > 0) {
space after `if`

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +        if(weighted) {
space after `if`

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +        if(nrow(matrix.data)>1) { # for a 1x1 matrix ordering does not work
space after `if` and before and after `>`

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +        if(nrow(matrix.data)>0) {
space after `if` and before and after `>`

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +        if(!weighted) {
space after `if`

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +    array <- array(data = 0, dim=c(nrow(adjacency.list[[1]]), nrow(adjacency.list[[1]]), length(adjacency.list)))
replace `<-` by `=`.
space before and after `=`
(this also holds for the following 20 lines....

2020-08-24 21:44 UTC, bockthom commented on util-networks-misc.R
> +    # create a 3-dimensional array representing the adjacency matrices (SIENA data format) as result
According to our coding conventions, "comments on an own line start with two hash signs (`##`)". Also holds for the comments several lines below.

2020-08-24 21:44 UTC, bockthom commented on util-tensor.R
> +        build.tensor.from.networks = function(networks, weighted = FALSE) {
default value missing in documentation of this function :smile:

2020-08-24 21:44 UTC, bockthom commented on util-tensor.R
> +      if(igraph::vcount(retrieved.network) > 0){
space after `if`

2020-08-24 21:44 UTC, bockthom commented on util-tensor.R
> +#' Calculate EDCPTD centrality for a given forth-order tensor.
Could you please phrase this in a way like it is done here: https://github.com/se-passau/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-networks-metrics.R#L128-L132

2020-08-24 21:46 UTC, bockthom commented on util-tensor.R
> +  decomposition <-rTensor::cp(forth.order.tensor$get.tensor(), num_components = 1, max_iter = 50, tol = 1e-05)
Then just explain why you have chosen `num_components = 1` and state that you have taken the default values of the other two parameters.

2020-08-24 21:47 UTC, bockthom commented on util-tensor.R
> +get.expanded.adjacency = function(network, authors, weighted = FALSE) {
That's fine for the moment (as far as they don't lead to compile errors and calling them separately does not lead to an error). However, there are still some functions missing or not in their recent version -- please have a look at my particular comments on that below.

2020-08-24 21:49 UTC, bockthom commented on util-tensor.R
> +get.author.networks = function(network.builder, relations) {
No worries, just keep this function as it is. (Removing it later would not be a problem for us, but adding it if it would not exist would be way more effort for us. As you have used it for testing reasons etc., just keep this function.)

2020-08-24 21:50 UTC, bockthom commented on util-tensor.R
> +       private$dim = c(length(private$authors), length(private$relations), length(private$authors), length(private$relations))
Ok, I understand. But imagine that there would be someone who would like to access the dimension later on -- in such a case it would be useful to have a getter for it...

2020-08-24 21:53 UTC, bockthom commented on util-tensor.R
> +                    ## transfer the entries from the adjacency matrix the tensor
Shouldn't it be "from the adjacency matrix **to** the tensor" or something similar? some word seems to be missing here...

2020-08-24 21:54 UTC, bockthom commented on util-tensor.R
> +                    ## matrix entries are shifted by one due to sparse matrix properties
That's not clear to me. Could you please add a (very small) explanation  for those shifting / sparse matrix properties?

2020-09-19 09:39 UTC, fehnkera commented on util-init.R
> +source("util-tensor.R")
You wrote in the description part `util-networks-metrics.R'`. Instead of `util-networks-misc.R`. Was this just a tipping mistake or is this on purpose?

2020-09-19 09:42 UTC, fehnkera commented on util-init.R
> +source("util-tensor.R")
Additionally the order in the files `util-init.R` and `README.md` is already before my PR not the same. I have just added the two new files to a in my opinion suitable place. If we want to have the same order in `util-init.R` and `README.md` we should change it in a seperate PR

2020-09-19 09:48 UTC, bockthom commented on util-init.R
> +source("util-tensor.R")
> You wrote in the description part `util-networks-metrics.R'`. Instead of `util-networks-misc.R`. Was this just a tipping mistake or is this on purpose?

This was a mistake, it should be `util-networks-misc.R` here. Sorry for that, thanks for spotting it!

2020-09-19 09:55 UTC, bockthom commented on util-init.R
> +source("util-tensor.R")
> Additionally the order in the files `util-init.R` and `README.md` was already before my PR not the same. I have just added the two new files to a in my opinion suitable place. If we want to have the same order in `util-init.R` and `README.md` we should change it in a separate PR

As you already touch both files in this PR, we should introduce the new changes in a consistent order. You are right, the order was already inconsistent before. However, I don't care about the order of the remaining files, but only about the order of the files which are in some kind relevant for this PR - and it is not a big effort to arrange those four lines into the same order in both files. It is easier doing it now as we already touch those parts of the code than postponing it. So, I hope you are fine with my answer :wink:

2020-09-19 10:38 UTC, fehnkera commented on util-init.R
> +source("util-tensor.R")
Okay, I will do it. Thank you for your fast answer!

2020-09-19 10:48 UTC, fehnkera commented on util-networks-misc.R
> +
I couldn't find a copyright header for Angelika in coronet yet. I have just added `## Copyright 2017 by Angelika Schmid <schmidang@fim.uni-passau.de>`. Is this correct or shall I use a different email?

2020-09-19 11:04 UTC, bockthom commented on util-networks-misc.R
> +
Should be fine :smile:

2020-09-19 12:32 UTC, fehnkera commented on util-networks-misc.R
> +}
Are this the wanted functions from Jakob? Is there anything in this functions that has to be adjusted for `coronet`?

2020-09-19 12:34 UTC, fehnkera commented on util-networks-misc.R
> +get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
Is this the wanted "companion function"? I'm actually not sure what a cumulated adjacency matrix is, so I just coppied the code from `dev-network-growth`. Is there anything I need to change?

2020-09-19 12:35 UTC, fehnkera commented on util-networks-misc.R
> +get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
In addition, according to git blame did also @clhunsen worked at this code. So I guess he should be part of the copyright too?

2020-09-19 12:37 UTC, fehnkera commented on util-tensor.R
> +                    array[matrix@i[entry] + 1, l, matrix@j[entry] + 1, l] = matrix@x[entry]
Is this documentation clear enough or shall I explain it further?

2020-09-19 12:42 UTC, fehnkera commented on README.md
>  - `tests.R`
Is this the wanted position? Or even after `showcase.R` and `tests.R` ?

2020-09-19 12:48 UTC, bockthom commented on util-networks-misc.R
> +}
> Are this the wanted functions from Jakob? Is there anything in this functions that has to be adjusted for `coronet`?

Yes, these are the functions I have meant. As far as I can see now, these functions are in compliance with our coding conventions. Hence, there is no need to adjust these functions.

2020-09-19 12:59 UTC, bockthom commented on util-networks-misc.R
> +get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
> Is this the wanted "companion function"? I'm actually not sure what a cumulated adjacency matrix is, so I just coppied the code from `dev-network-growth`. Is there anything I need to change?

Yes, this is the companion function I was looking for :wink: And there is no need to change anything in this function -- you could just remove the unnecessary blank line in line 169 :smile: 

What the function does is stated in its comments: It sums up the adjacency matrices cumulatively, that's why it is called "cumulative" adjacency matrix. So, the return value is a list (as long as the list of networks). The first element of this list is just the first adjacency matrix, the second element is the sum of the first and the second, the third element is the sum of first, second, and third adjacency matrix, and so on... Maybe you can add such a description to the documentation of this function, then it should be clear to everyone.

Nevertheless, please adjust the documentation of the return values of both `get.expanded.adjacency` and `get.expanded.adjacency.cumulated` because their return values are not a list of author names...

In addition, please use `get.expanded.adjacency` instead of `get_expanded_adjacency` within this function. (To spot mistakes like this one, it would be an idea to test the function call: For instance, build a list of two networks and pass it to this function, then it should run without errors...)

2020-09-19 13:00 UTC, bockthom commented on util-networks-misc.R
> +get.expanded.adjacency.cumulated = function(networks, weighted = FALSE) {
> In addition, according to git blame did also @clhunsen worked at this code.

This is correct, so please add him.

2020-09-19 13:03 UTC, bockthom commented on util-networks-misc.R
> +    array = array(data = 0, dim=c(nrow(adjacency.list[[1]]), nrow(adjacency.list[[1]]), length(adjacency.list)))
I did not review your new changes yet, but as I just spotted this one, I am commenting right away:

Here the coding conventions are still violated: Spaces around `=` are missing. This also holds for the `which` statement below and for the `for` loops in this function.

2020-09-19 13:06 UTC, bockthom commented on util-tensor.R
> +                    array[matrix@i[entry] + 1, l, matrix@j[entry] + 1, l] = matrix@x[entry]
To the best of my knowledge, array indexes in R start at `1`. Please check that again and make sure that both your implementation and documentation are correct.

2020-09-19 13:10 UTC, bockthom commented on README.md
>  - `tests.R`
> Is this the wanted position? Or even after `showcase.R` and `tests.R` ?

Unfortunately, it's not. Sorry if I have confused you a little bit with my comments before. As this related to "networks", `util-networks-misc.R` and `util-tensor.R` should be listed right after `util-networks-metrics.R`.

Please use `util-networks-misc.R` and *not* `misc`**`s`** - the s is to much here.

2020-09-19 13:12 UTC, bockthom commented on util-tensor.R
> +
Again, as I just spotted this by chance: Please don't forget to fix the indentation in this function :wink: 
Please double-check also for the other functions that the indentation is correct.

2020-09-19 16:17 UTC, fehnkera commented on util-tensor.R
> +                    array[matrix@i[entry] + 1, l, matrix@j[entry] + 1, l] = matrix@x[entry]
Oh yes I mixed it up, thank you! It is kind of the other way around. For some reason start the indexes saved in the sparse matrix with 0 (even though the indexes of the sparse matrices start with 1). So an entry matrix in the sparse matrix is i.e. saved at i=0, j= 0 and has to be transferred to the array at i=1, j=1. In my opinion stupid implementation in the sparse matrix but therefore is the shift needed.

2020-09-19 17:41 UTC, fehnkera commented on util-tensor.R
> +
Thank you! I'll double-check my work tomorrow morning and  let you know afterwards, so you can start your review if you want :)

2020-09-20 07:37 UTC, fehnkera commented on util-tensor.R
> +
Unfortunately I only had the time for a rough double-check this morning and don't have time for the rest of the day. I will do a detailed one tomorrow.

2020-09-20 11:22 UTC, bockthom requested changes
Thanks a lot @fehnkera. This pull request now goes into the right direction :smile: I think we are already close to finishing this PR, but there are still some issues. I hope that this is the last review of this PR, as most things really look good -- but let's see how you address my comments.

In general, there are four remaining issues:

1. Minor issues (documentation, function calls, etc.): I spent some time on looking at all the outdated review comments and checked for each of them, which one you already had addressed and which one still is not addressed (yes, there were a lot of comments by @clhunsen and me in this PR, so I spent more time on that than expected...). As it was even time-consuming for me to find the unaddressed comments, I marked all the outdated but not yet addressed comments as "resolved" and added them as new comments to this review -- that makes it easier for you (and also for me) to see what still needs to be changed :wink: So, please see the individual comments below.

2. There is one problem in the implementation I have spotted right now: Your implementation of `get.expanded.adjacency` operates on a single network only, whereas Angelika's version operated on a list of networks. Hence, the function `get.expanded.adjacency.cumulated` does not work at the moment. However, this is easy to fix via introducing an additional function -- I have provided a description for a fix already in my comments below.

3. Commit messages: After fixing all the things mentioned in my comments, please adjust the commit messages (via interactive rebasing): 
The commit "Changes process of calculating EDCPTD centrality" needs to be renamed to "Change process of calculating EDCPTD centrality" (Change instead of Changes).
And in the latest commit, your Signed-off tag does not contain your name - please replace "fehnkera" by your name there. Thanks!

4. Last but not least: After you have fixed all the problems within this pull request, we need to make this pull request ready to be merged. Therefore, it needs to have the correct base (that it uses not the correct base can you see at Claus's merge commits showing up in your PR). Your branch "fehnkera:tensor" still has the wrong base: It is based on master, not on dev. Therefore, please checkout the current `dev` branch and rebase your changes of this PR onto it, resulting in only having your commits in this PR. After that, please don't forget to update the changelog file (it is important to do that after your last rebase as commit hashes change during rebasing.) And then, your PR should be ready to merge :wink: But before that, I will check if issues 1, 2, and 3 are addressed correctly - step 4 is really the final step after everything else has been fixed.

If you have any questions regarding my comments or regarding rebasing onto `dev` branch, just don't hesitate to ask. The end of this PR already is in sight, only few steps missing :smile:

2020-09-22 19:36 UTC, bockthom commented on util-networks-misc.R
> +#' Get a sparse adjacency matrix for a network.
Please don't forget to add the missing description I have provided in my previous comment.

2020-09-22 19:39 UTC, bockthom commented on util-networks-misc.R
> +#' All adjacency matrix have the same authors.
All adjacency matri**ces** are expanded in such a way that the use the same set of authors derived from all networks in the list.

2020-09-22 19:40 UTC, bockthom commented on util-networks-misc.R
> +    authors = get.authors.from.networks(networks)
This won't work as the function is called `get.author.names.from.networks` (if I remember correctly).

2020-09-22 19:42 UTC, bockthom commented on util-tensor.R
> +requireNamespace("rTesnor") # tensors
Should be `"rTensor"`, not `"rTesnor"`.

2020-09-23 16:35 UTC, fehnkera commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
Unfortunately, I get an exception saying `argument to 'which' is not logical` when I test this function. Do you have any experience with this function and have an idea why this occurs and how to fix it?

Further am I not sure if the arbitrary number really is the best solution here.

2020-09-23 16:36 UTC, fehnkera commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
Should we actually also check for issue activities here?

2020-09-24 09:09 UTC, bockthom commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
At the moment, I don't no how exactly this can happen. Could you please provide some details how you have executed and tested this function, in particular which inputs you have used? Having more information would help us to find out what's going :wink:

2020-09-24 09:10 UTC, bockthom commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
In addition, there are some spaces around the minus sign missing in lines 188 and 189 :wink:

2020-09-24 09:17 UTC, bockthom commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
Good point, sounds like a good idea. I would suggest to replace the parameter `is.mail.analysis` by `data.source` where `data.source` can either be `"commits"`, `"mails"`, or `"issues"`, or any combination of them.

Then you could use the `match.arg.or.default` function to make sure that the argument is either of these three, the default should be the full vector `c("commits", "mails", "issues")`.
Then you could just check whether "commits" etc. is contained in the parameter vector and if so extract the authors and unify them afterwards.

2020-09-24 18:18 UTC, clhunsen commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
We could use the method `ProjectData::get.authors.by.data.source` directly instead of re-inventing the wheel. :wink: 

https://github.com/se-passau/coronet/blob/91fc448bad64dd17fa96a720322fe7d46337cc43/util-data.R#L1316-L1339

2020-09-27 17:00 UTC, fehnkera commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
Thanks for the missing spaces :)

2020-09-27 17:42 UTC, fehnkera commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
I just used the list of the three networks that I use to build the tensor. So one list with with cochange, one list with mail and one list with issue data. everything until the `which` statement works. So I guess the problem should be somewhere in the which statement.

Also if I set `weighted = TRUE` the complete function works.

2020-09-27 17:44 UTC, fehnkera commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
Maybe it helps if I understand the which statement. What exactly are we doing here. Don't we just want to set all non-zero entries to 1? Isn't this done by the last line `matrices.cumulated[[m]]@x = rep(1, length(matrices.cumulated[[m]]@i))`? Why do we need the lines before?

2020-09-27 17:47 UTC, fehnkera commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
Thank you for your suggestion @clhunsen. I just implemented and tested it and it works so far. Could you have quick look if it is implemented like you suggested?

2020-09-27 20:01 UTC, bockthom commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
Some time ago, setting all the non-zero weights to 1 did not work due to unknown reasons (maybe a bug in the implementation of sparse matrices). I don't know whether this bug still can occur or whether it is already fixed in the `Matrix` package. As it did not work, we searched for a work-around, and in November 2017 we (@clhunsen and me) found that manually setting one non-zero entry to an arbitrary number led to not triggering the bug anymore when setting all non-zero entries to 1 afterwards. This is why we have these arbitrary number 42.

What the `which` statement does is the following:
Get all the indexes of the entries whose values are >=1 in the sparse matrix. Then we can use these indexes to find one non-zero entry which we can manually set to an arbitrary number afterwards to prevent the bug described above.

2020-09-28 18:43 UTC, fehnkera commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
Okay, thank you for the explanation. I repeated my test and for some reason it works now. I have no idea why because I have not changes anything. Maybe it was just a mistake with my R session?

2020-09-28 19:25 UTC, fehnkera commented
Okay, I think I have completed the four remaining issues now @bockthom. Is there anything else that needs to be done in this PR?

2020-09-28 19:43 UTC, bockthom commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
Looks good to me, nice implementation @fehnkera @clhunsen. However, I don't think that we need that much blank lines here. So, for me it would be fine to remove lines 78 and 80 and have three statements in a row, as all three lines are related to each other. And I spotted two minor mistakes in the documentation, which I will add as separate comments.

2020-09-28 19:55 UTC, bockthom commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
The parameter is called `data.source`, not `data.sources`.  In addition, we should add the following:
`the data sources from which the author names should be retrieved, can be either \code{"commits"}, \code{"mails"}, or \code{"issues"}, or any combination of them [default: c("commits", "mails", "issues")]`. (Don't forget to add a line break as this line would exceed 120 characters I guess.)

However, I just spotted a bug in this function: This function does not work for multiple data sources. For that, we need to set the parameter `several.ok = TRUE` in the function call `match.arg.or.default`. However, this does still not work as the function `get.authors.by.data.source` only returns the values for one data source, not for multiple data sources... this needs to be fixed, I guess. We could fix this here by adding multiple calls to `get.authors.by.data.source` to iterate over the vector of data sources and call unique afterwards. (Alternatively, this could be fixed directly in `get.authors.by.data.source` but this may lead to failing tests and unwanted behavior somewhere else...).

2020-09-28 19:56 UTC, bockthom commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
This comment is outdated as `commit/mail` does not incorporate `issue event`

2020-09-28 20:02 UTC, bockthom commented
> Okay, I think I have completed the four remaining issues now @bockthom. Is there anything else that needs to be done in this PR?

There are some minor issues in the one function getting the names, but when they are fixed, I think we are done with this PR, if @clhunsen agrees. However, after rebasing your last commit for the last time, you need to add your adjustments to the changelog file `NEWS.md` which should be the very last step before merging.

If you are still willing to work on this PR you could write tests for it. Otherwise (if you already run out of working hours), we are done with this PR as soon as the last bugs are fixed and the changelog file is adjusted in a reasonable way :wink:

2020-09-29 21:37 UTC, clhunsen commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
The function has not worked on multiple data sources [in earlier versions of this patch](https://github.com/se-passau/coronet/commit/56b776f850a9ca3acdfbe8dcba8b28362ffe88e2#diff-cc8c30169d62ac5a529208d47c6e21f2R63-R96). Thus, I am not sure whether it is needed to make it work this way. If it is needed, we do not need to worry about tests when changing the method `get.authors.by.data.source` as there are no direct tests of this functionality (as far as I know).

2020-09-29 21:59 UTC, bockthom commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
> The function has not worked on multiple data sources in earlier versions of this patch. Thus, I am not sure whether it is needed to make it work this way. 

This is true @clhunsen. However, as we decided to adjust this function to work for different data sources, we also should make it work for multiple data sources when we already touch this function now.

> If it is needed, we do not need to worry about tests when changing the method `get.authors.by.data.source` as there are no direct tests of this functionality (as far as I know).

I don't know, we will see :wink: In the end, I would like to have a fast solution needing less effort but being able to do all the stuff also for multiple data sources. If this works, I am fine with it :partying_face:

2020-09-29 21:59 UTC, clhunsen commented on util-networks-misc.R
> +                not.zero.idxs = which(matrices.cumulated[[m]] >= 1, arr.ind = TRUE)
This is one of the reasons why we have test suite that is to be executed in a quasi-vanilla R environment. :wink: And yes, restarting your R session is always good in the context of weird behavior.

2020-09-30 08:38 UTC, clhunsen commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
> > The function has not worked on multiple data sources in earlier versions of this patch. Thus, I am not sure whether it is needed to make it work this way.
> 
> This is true @clhunsen. However, as we decided to adjust this function to work for different data sources, we also should make it work for multiple data sources when we already touch this function now.

Ah, sorry, I may have missed the corresponding discussion. My fault. 

> > If it is needed, we do not need to worry about tests when changing the method `get.authors.by.data.source` as there are no direct tests of this functionality (as far as I know).
> 
> I don't know, we will see :wink: In the end, I would like to have a fast solution needing less effort but being able to do all the stuff also for multiple data sources. If this works, I am fine with it :partying_face:

I searched for the function in the code base and found [only one use case](https://github.com/se-passau/coronet/blob/75ae4a505b36bd73f554a982645c82171c808618/util-networks.R#L193-L204) – where the parameter `data.source` is set appropriately.

Basically, only few steps are needed to adjust `get.authors.by.data.source` accordingly to process multiple data sources at once:
- [ ] Allow several data sources (`match.arg.or.default`).
- [ ] Adjust default value to contain multiple `data.sources` or set it accordingly in the call to `match.arg.or.default`. In the first case, be sure to adjust the one use case linked above.
- [ ] Wrap the current data processing in an `lapply` statement running along the parameter `data.sources`.
- [ ] Run `plyr::rbind.fill` after the `lapply` call.
- [ ] Leave the removal of duplicates where it is.
- [ ] Adjust the documentation appropriately.

2020-10-06 17:25 UTC, bockthom commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
I had a more detailed look at this function. Your approach sounds good @clhunsen. Let's implement it in the way as you have suggested  for `get.authors.by.data.source` and then just adjust the function call within `get.author.names.from.data`.
@fehnkera Could you please adjust the two functions (making use of Claus's descriptions)? Thanks!

2020-10-07 11:40 UTC, fehnkera commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
Thank you for this good instructions @clhunsen! I think I have applied them.

However I had two problems:
1. I am not sure how the use case shall be adjusted. Shall I just change `data.source` to `data.sources` or is there anything else?
2. For some reason I get an error if I want to retrieve issue or mail data. The error message for mails says ` Error in if (private$project.conf$get.value("mails.filter.patchstack.mails")) { : argument is of length zero `  and the error message for issues says `Error: Argument 'txt' must be a JSON string, URL or file.` (I think the function tries to find both, jira and github issue files, even through only jira issues exist). Do you know why I get this errors? Is this my R session again?

2020-10-07 11:53 UTC, bockthom commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
> Thank you for this good instructions @clhunsen! I think I have applied them.

You have applied them, as far as I have seen. However, you may have missed by comment regarding one comment (see separate comment below).
> 
> However I had two problems:
> 
>     1. I am not sure how the use case shall be adjusted. Shall I just change `data.source` to `data.sources` or is there anything else?

Good point, I don't see anything else. So should be fine with your implementation. Or did I miss something @clhunsen ?

However, @fehnkera please make the parameter names consistent: in the one function it is now called `data.source` (in `get.author.names.from.data`), in the other one `data.sources` (in `get.authors.by.data.source`). Make sure that the parameter name is used consistently in both functions (and their documentations) and their respective calls.
> 
>     2. For some reason I get an error if I want to retrieve issue or mail data. The error message for mails says `Error in if (private$project.conf$get.value("mails.filter.patchstack.mails")) { : argument is of length zero`  and the error message for issues says `Error: Argument 'txt' must be a JSON string, URL or file.` (I think the function tries to find both, jira and github issue files, even through only jira issues exist). Do you know why I get this errors? Is this my R session again?

Hm. I don't understand the error messages here. Could you try a new R session again? Otherwise, please let us know which data you have used here.

In addition, don't forget to add yourself to the Copyright header in all files you have changed (so, the one containing the function `get.authors.by.data.source`). Also in `showcase.R` it is missing, if I have not overlooked it.

2020-10-07 11:53 UTC, bockthom commented on util-networks-misc.R
> +    ## for each range, get the authors who made at least one commit/mail in this range
Please fix the comment here. You might have overlooked that :wink:

2020-10-07 15:10 UTC, clhunsen commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
Nice implementation, @fehnkera! Good work on this and also the complete PR! :slightly_smiling_face::+1: 

> > However I had two problems:
> > 
> > 1. I am not sure how the use case shall be adjusted. Shall I just change `data.source` to `data.sources` or is there anything else?
> 
> Good point, I don't see anything else. So should be fine with your implementation. Or did I miss something @clhunsen?

No, there is nothing else. Just change `data.source = "commits"` to `data.sources = "commits"`.

> However, @fehnkera please make the parameter names consistent: in the one function it is now called `data.source` (in `get.author.names.from.data`), in the other one `data.sources` (in `get.authors.by.data.source`). Make sure that the parameter name is used consistently in both functions (and their documentations) and their respective calls.

Please change the parameter name to `data.sources` in the function `get.author.names.from.data`.

> > 2. For some reason I get an error if I want to retrieve issue or mail data. The error message for mails says `Error in if (private$project.conf$get.value("mails.filter.patchstack.mails")) { : argument is of length zero`  and the error message for issues says `Error: Argument 'txt' must be a JSON string, URL or file.` (I think the function tries to find both, jira and github issue files, even through only jira issues exist). Do you know why I get this errors? Is this my R session again?
> 
> Hm. I don't understand the error messages here. Could you try a new R session again? Otherwise, please let us know which data you have used here.

Hm, I have not seen that error before either. Seems to be an error due to an outdated or corrupted `ProjectConf` object. Cleaning your environment may help (e.g., call `rm(list = ls())` in the current session).

2020-10-14 19:38 UTC, fehnkera commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
Okay, after trying out different things with my R session and `ProjectConf` in the last days I got it finally working (Switching the project and then switching back helped). But the good news is that this function works as expected. So now I hopefully have everything done apart of the final adjustment of the `News.md` file. Or is there anything that I have overlooked? The time that I have left is already processed by now, but I will of course work on this PR until it is finally merged :)

2020-10-16 12:20 UTC, bockthom commented on util-networks-misc.R
> +#' @param data.sources sources from which the authors shall be retrieved [default: c("commits", "mails", "issues")]
Sounds good! Thanks for all your efforts @fehnkera. I have reviewed your current changes again and everything looks good to me now :smile: 
So, rebasing the last commit has finished now, no need for further rebases any more :wink: 

Last but not least, the changelog file needs to be adjusted, but this should become a separate commit. I will provide a draft what I would like to appear in the changelog below.

2020-10-16 13:03 UTC, bockthom submitted a review, later dismissed
Finally, we need to adjust the changelog. I have provided a draft for the changelog, please check if this is correct:

 - [ ] Add a new line `## Unversioned` above version 3.6.
 - [ ] Add a new section `### Added` below `## Unversioned`
 - [ ] Add the following bullet points:

```
- Add a new file `util-tensor.R` containing the class `FourthOrderTensor` to create (author x relation x author x relation) tensors from a list of networks (with each network having a different relation) and its corresponding utility function `get.author.networks.for.multiple.relations` (PR #173, c136b1f6127d73c25f08ae2f317246747aa9ea2b, e4ee0dc926b22ff75d5fd801c1f131bcff4c22eb, 051a5f0287022f97e2367ed0e9591b9df9dbdb3d)
- Add function `calculate.EDCPTD.centrality` for calculating the EDCPTD centrality for a fourth-order tensor in the above described form (c136b1f6127d73c25f08ae2f317246747aa9ea2b, e4ee0dc926b22ff75d5fd801c1f131bcff4c22eb, 051a5f0287022f97e2367ed0e9591b9df9dbdb3d)
- Add new file `util-networks-misc.R` which contains miscellaneous functions for processing network data and creating and converting various kinds of adjacency matrices: `get.author.names.from.networks`, `get.author.names.from.data`, `get.expanded.adjacency`, `get.expanded.adjacency.matrices`, `get.expanded.adjacency.matrices.cumulated`, `convert.adjacency.matrix.list.to.array` (051a5f0287022f97e2367ed0e9591b9df9dbdb3d)

```

- [ ] Add a new section `### Changed/Improved`
- [ ] Add the following bullet points in the Changed/Improved section:

```
- Adjust the function `get.authors.by.data.source`: Rename its single parameter to `data.sources` and change the function so that it can extract the authors for multiple data sources at once. The default value of the parameter is a vector containing all the available data sources (commits, mails, issues) (051a5f0287022f97e2367ed0e9591b9df9dbdb3d)
```

Please check if this is correct and whether I have forgotten anything.

2020-10-18 12:30 UTC, fehnkera commented
Thank you very much for this good draft @bockthom ! I checked it and everything seems to be correct. I hope I have implemented it in the wanted way.

Overall I have to say thank you to all of you @bockthom @clhunsen @ecklbarb ! Thank you for your patience and your really good help. I have learned a lot by working with you.

And again I am very sorry that this PR took so much time!

2020-10-19 20:52 UTC, clhunsen commented
> Overall I have to say thank you to all of you @bockthom @clhunsen @ecklbarb ! Thank you for your patience and your really good help. I have learned a lot by working with you.

It was a pleasure working with you, @fehnkera! Good luck and all the best for everything that is ahead of you! Take care, Anselm. 🥲:hugs:

> Thank you very much for this good draft @bockthom ! I checked it and everything seems to be correct. I hope I have implemented it in the wanted way.

That is your part, @bockthom! Merge if everything is okay for you. :slightly_smiling_face::+1:

2020-10-29 07:44 UTC, bockthom commented
> That is your part, @bockthom! Merge if everything is okay for you. slightly_smiling_face+1

Sorry for the late reply, I had vacation for the last weeks. I just had a look at this PR right now. Looks good, except for one minor issue:

@fehnkera The signed-off tag is missing in your last commit 55ad8d8. Could you please add the signed-off tag to your commit message? Thanks in advance. This will be the final change, I will merge this PR right afterwards :smile: 


> > Overall I have to say thank you to all of you @bockthom @clhunsen @ecklbarb ! Thank you for your patience and your really good help. I have learned a lot by working with you.
> > Thank you very much for this good draft @bockthom ! I checked it and everything seems to be correct. I hope I have implemented it in the wanted way.

Also thanks to you @fehnkera for all of your work and, especially, also for your endurance (that's not to be taken for granted). Working on this last PR took longer than expected (for all of us, I'll guess) and also getting familiar with all the details again (as this PR was opened one year ago) was tedious for everyone. However, finally, we have added lots of useful functionality to coronet and this will definitively improve the future use of coronet. So, I am glad that we will finally merge this PR soon. I hope you enjoyed the work on coronet (even though there were lots of reviews and change requests) and also hope that your work effort also comes along with good working experiences for you. I and also the whole @se-passau/codeface-admins team wish you all the best for your future. :balloon:

2020-10-29 13:23 UTC, fehnkera commented
> Sorry for the late reply, I had vacation for the last weeks. I just had a look at this PR right now. Looks good, except for one minor issue:

No problem. I hope you had a nice vacation :smile: 
> 
> @fehnkera The signed-off tag is missing in your last commit [55ad8d8](https://github.com/se-passau/coronet/commit/55ad8d83084f12a22a30eecaea9867541d91704e). Could you please add the signed-off tag to your commit message? Thanks in advance. This will be the final change, I will merge this PR right afterwards smile
> 
Oh yes, sorry. I will add this right away!
> 
> Also thanks to you @fehnkera for all of your work and, especially, also for your endurance (that's not to be taken for granted). Working on this last PR took longer than expected (for all of us, I'll guess) and also getting familiar with all the details again (as this PR was opened one year ago) was tedious for everyone. However, finally, we have added lots of useful functionality to coronet and this will definitively improve the future use of coronet. So, I am glad that we will finally merge this PR soon. I hope you enjoyed the work on coronet (even though there were lots of reviews and change requests) and also hope that your work effort also comes along with good working experiences for you. I and also the whole @se-passau/codeface-admins team wish you all the best for your future. :balloon:

Yes, i have definitely enjoyed the work and gained very good working experiences. Thank you!

2020-10-29 17:04 UTC, fehnkera commented
Is there any reason why the checks have failed now? All I did was changing the commit message of the last commit :sweat_smile:

2020-10-29 17:13 UTC, bockthom commented
> Is there any reason why the checks have failed now? All I did was changing the commit message of the last commit sweat_smile

I just checked the travis builds a few minutes ago and found out that this is a general problem with travis using certain R versions, as it also fails for the current `master` and `dev` branches. However, the builds are successful for R version 3.6 but not for previous R versions, which is weird. The reason why the checks fail is that the log output of the test runs is too large for travis, so it just terminates the build runs before they are finished.

Thanks for asking, but this is definitively not related to your changes, but rather to our build configuration. So no worries, everything is fine with your PR :smile:  I will try to deal with the build problems as soon as I have time to do that. This is not part of this PR.

2020-11-08 22:54 UTC, bockthom commented
As the build errors of the Travis CI check are not related to this pull request (as already stated above and later on partly discussed in #161), I will merge this PR right away (despite having failing builds here) -- the Travis build problems are going to be fixed very soon in another PR, I already have implemented some fixes for these problems.
So, after more than one year of working on integrating the new enhancements of @fehnkera, I am glad to finally incorporate them into coronet now :tada:

2020-11-08 22:54 UTC, bockthom approved these changes

2020-11-08 22:56 UTC, merged